// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD526x-2ypVJdz0NkF2R0t2kbp60njCIj0',
    appId: '1:1030856665327:web:620c19460440302a4e531a',
    messagingSenderId: '1030856665327',
    projectId: 'cbyk-cda5a',
    authDomain: 'cbyk-cda5a.firebaseapp.com',
    storageBucket: 'cbyk-cda5a.firebasestorage.app',
    measurementId: 'G-NFLGX1L0HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGLjXKAeS4Qq4YSJwBV08hq5eB0CCR8YQ',
    appId: '1:1030856665327:android:3931969de23cc1154e531a',
    messagingSenderId: '1030856665327',
    projectId: 'cbyk-cda5a',
    storageBucket: 'cbyk-cda5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4bO9SRP30BulDFAsVxeVWZQ7c39hdGHU',
    appId: '1:1030856665327:ios:110426e9d71e5ce74e531a',
    messagingSenderId: '1030856665327',
    projectId: 'cbyk-cda5a',
    storageBucket: 'cbyk-cda5a.firebasestorage.app',
    iosBundleId: 'com.example.cbykTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4bO9SRP30BulDFAsVxeVWZQ7c39hdGHU',
    appId: '1:1030856665327:ios:110426e9d71e5ce74e531a',
    messagingSenderId: '1030856665327',
    projectId: 'cbyk-cda5a',
    storageBucket: 'cbyk-cda5a.firebasestorage.app',
    iosBundleId: 'com.example.cbykTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD526x-2ypVJdz0NkF2R0t2kbp60njCIj0',
    appId: '1:1030856665327:web:fa35740b800304094e531a',
    messagingSenderId: '1030856665327',
    projectId: 'cbyk-cda5a',
    authDomain: 'cbyk-cda5a.firebaseapp.com',
    storageBucket: 'cbyk-cda5a.firebasestorage.app',
    measurementId: 'G-PZC08R28D9',
  );
}
